### ISSUE TITLE
[EVENT] 창에서 X 버튼으로 프로그램 종료 시 프로세스가 종료되지 않는 문제

### ISSUE THREAD

**Issue by junyoung2015** [044apde/cub3D#1]
## 작업 설명

<img width="499" alt="image" src="https://github.com/044apde/cub3D/assets/14016311/3b3b4346-1e40-48e3-a098-2cf3012856c7">

- 윈도우 창에서 좌측 상단 x 버튼을 눌렸을 때 창이 꺼지지만 프로세스는 종료되지 않아 ESC 를 눌렀을 때와 동일하게 종료되도록 mlx_hook 을 추가로 부르려고 합니다.

**Comment by 044apde** [comment]
good
